version: '3'

services:
  api:
    image: snippet-management
    ports:
      - '${Ports__ApiAppPort}:80'
    environment:
      ConnectionStrings__DefaultConnection: Server=db;Database=SnippetManagement;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true
      Jwt__ValidAudience: snipman.azurewebsites.net
      Jwt__ValidIssuer: snipman.azurewebsites.net
      Jwt__IssuerSigningKey: ${JWT_ISSUER_SIGNING_KEY}
      Jwt__ExpiringDays: 1
      Ports__ApiAppPort: ${Ports__ApiAppPort}
      Ports__ReactAppPort: ${Ports__ReactAppPort}
      Cors__AllowOrigins: ${Cors__AllowOrigins}
      ASPNETCORE_URLS: http://*:${Ports__ApiAppPort}