version: '3'

services:
  api:
    image: snippet-management
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: Server=db;Database=SnippetManagement;User Id=sa;Password=MyPassword123!;TrustServerCertificate=true
      Jwt__ValidAudience: http://localhost:${API_PORT}
      Jwt__ValidIssuer: http://localhost:${API_PORT}
      Jwt__IssuerSigningKey: ByYM000OLlMQG6VVVp1OH7Xzyr7gHuw1qvUC5dcGt3SNM
      Jwt__ExpiringDays: 1
      ASPNETCORE_URLS: http://*:${API_PORT}
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - snippet-management-vol:/var/opt/mssql
    ports:
      - '5000:1433'
    environment:
      MSSQL_SA_PASSWORD: MyPassword123!
      ACCEPT_EULA: 'Y'
  web:
    image: snippet-management-web
    ports:
      - '${WEB_PORT}:3000'
    environment:
      REACT_APP_GOOGLE_CLIENT_ID: 448086775090-g62vpn8qbig7gqt2qiin9m6ok5sgislk
      REACT_APP_BASE_URL: http://localhost:${API_PORT}/
volumes:
  snippet-management-vol: