name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "BackEnd/**"
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - "BackEnd/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:  ${{ github.ref == 'refs/heads/master' && 'Production' || 'Staging' }}

    env:
      REACT_APP_BASE_URL: https://${{ vars.AZURE_APP_NAME }}.azurewebsites.net
      REACT_APP_GOOGLE_CLIENT_ID: ${{ vars.REACT_APP_GOOGLE_CLIENT_ID }}

    name: Build and Deploy
    if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/FrontEnd/snippet_management.web"
          output_location: "build"
          
