# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - master
      - develop
    paths-ignore:
      - 'FrontEnd/**'
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - 'FrontEnd/**'
  workflow_dispatch:
  
# env: 
#   AZURE_RESOURCE_GROUP: snipman
#   AZURE_APP_NAME: snipman-api
#   AZURE_APP_NAME_STAGING: snipman-api-staging
#   AZURE_APP_SERVICE_PLAN: /subscriptions/b20b8693-f2e0-4702-90fb-0a41106a70f0/resourceGroups/snipman/providers/Microsoft.Web/serverFarms/ASP-snipman-b218
#   AZURE_SUBCRIPTION: b20b8693-f2e0-4702-90fb-0a41106a70f0
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet build BackEnd/SnippetManagement.Api.sln --configuration Release    
      
    - name: Test
      run: dotnet test BackEnd/SnippetManagement.Api.sln --configuration Release --no-build --verbosity normal

  deploy_to_azure:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'Production' || 'Staging' }}
    needs: build

#     if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' }} 
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker login    
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push backend Docker images with staging version
      uses: docker/build-push-action@v4.1.0
      with:
        context: BackEnd/
        file: BackEnd/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/snippet-management-api-staging:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/snippet-management-api-staging:latest
        
    - name: Build and push frontend Docker images with staging version
      uses: docker/build-push-action@v4.1.0
      with:
        file: FrontEnd/snippet_management.web/Dockerfile
        context: FrontEnd/snippet_management.web/
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/snippet-management-web-staging:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/snippet-management-web-staging:latest

    - name: Azure CLI login and deploy
      uses: Azure/cli@v1.0.7
      with:
        inlineScript: |
          az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_APP_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set -s $AZURE_SUBCRIPTION
          az webapp create --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --plan ${{ vars.AZURE_APP_SERVICE_PLAN }} --name ${{ vars.AZURE_APP_NAME }} --deployment-container-image-name minhman97/snippet-management-api-staging:${{ github.sha }}
          echo deploy successfuly to ${{ vars.AZURE_APP_NAME }}
          
    - name: Setup backend env
      uses: Azure/cli@v1.0.7
      with:
        inlineScript: |          
          echo '${{ secrets.SETTINGS_BACKEND }}' > settings.json
          cat settings.json
          az webapp config appsettings set --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_APP_NAME_STAGING --settings @settings.json
  
